name: 'Code deploy GitHub Actions'
description: 'Create deployment via GitHub Actions'
author: 'Gabriel M. Dutra <gabriel@plugpagamentos.com'

inputs:
  application_name:
    description: 'The name of the ECS application'
    required: true

  deployment_config_name:
    description: 'The name of the Code Deploy deployment config'
    required: true

  cluster_name:
    description: 'The name of the ECS cluster'
    required: true

runs:
  using: 'docker'
  image: './Dockerfile'
